//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortalMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applystatu
    {
        public int id { get; set; }
        public int jobseekerid { get; set; }
        public string jobname { get; set; }
        public string status { get; set; }
    }
}
