//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortalMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppliedJobsStatu
    {
        public int Id { get; set; }
        public string Employername { get; set; }
        public string Jobname { get; set; }
        public string Status { get; set; }
        public int Jobseeker_id { get; set; }
    }
}
