//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortalMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLogin1
    {
        public int Log_id { get; set; }
        public int Reg_id { get; set; }
        public string user_type { get; set; }
        public string username { get; set; }
        public string password { get; set; }
    }
}
